import Foundation

/// Logical call media type. For the foundation pass we only emit "video"
/// (the user's stated v1 target), but the wire format already carries the
/// field so audio-only calls can land later without a protocol bump.
enum CallMedia: String, Codable {
    case audio
    case video
}

/// Direction this call started in, from *our* perspective. Drives whether
/// the UI shows the outgoing "calling…" surface or the incoming "accept /
/// decline" surface.
enum CallDirection: String, Codable {
    case outgoing
    case incoming
}

/// One end-to-end call, identified by `id` (UUID generated by the caller).
/// Both peers reference the same `id` in every signalling message so the
/// recipient can correlate offers with their answer / ICE / hangup.
struct Call: Identifiable, Hashable {
    let id: String
    let peerUIN: Int
    let peerNickname: String
    /// Mutable so a mid-call audio→video upgrade can flip `.audio` →
    /// `.video` on both peers without minting a new Call. The field
    /// drives which control row CallScreen renders (audio vs video
    /// chrome) and which renderer the parent ZStack picks.
    var media: CallMedia
    let direction: CallDirection
    let startedAt: Date

    init(
        id: String = UUID().uuidString.lowercased(),
        peerUIN: Int,
        peerNickname: String,
        media: CallMedia,
        direction: CallDirection,
        startedAt: Date = Date()
    ) {
        self.id = id
        self.peerUIN = peerUIN
        self.peerNickname = peerNickname
        self.media = media
        self.direction = direction
        self.startedAt = startedAt
    }
}
