import Foundation

/// One radio chat message. Ephemeral — never written to MessageDB.
/// Trimmed payload: text + optional reply + reactions, no media.
struct RadioMessage: Identifiable, Hashable, Codable {
    let id: String                   // UUID — generated by sender
    let senderDisplayName: String    // anonymous label inside the session
    let isFromMe: Bool
    let text: String
    let timestamp: Date
    let replyToID: String?
    let replyToSender: String?
    let replyToBody: String?
    /// `[reactor display name: asset name]`. One per name.
    var reactions: [String: String]
}

/// Wire format for `MCSession` messages. JSON-encoded per logical event.
/// Apple's MC already does TLS — this is purely the application envelope.
enum RadioPayload: Codable {
    case message(RadioMessage)
    case reaction(messageID: String, reactor: String, asset: String?)
    case challenge(roomID: String, ciphertext: Data)  // password gate
    case challengeAck(roomID: String, ok: Bool)
    case roster(displayName: String)                  // self-introduce on join
    /// PTT audio packet. AAC-LC frame (1024 PCM samples @ 16 kHz mono,
    /// ~24 kbps), sent `.unreliable` for latency. Drop-tolerant.
    case voiceFrame(speaker: String, seq: UInt32, data: Data)
    /// Reliably sent before first frame so receivers preallocate the
    /// player node and surface "X is talking" without waiting on audio.
    case voiceTalkStart(speaker: String)
    /// Reliably sent on PTT release — tears down receiver player node.
    case voiceTalkStop(speaker: String)
}

/// Outer wire frame. `.handshake` carries a raw Curve25519 public key
/// (plaintext, but Apple's MC TLS still protects the hop); `.sealed` is
/// AES-GCM ciphertext over a JSON `RadioPayload`. Frame tagging lets the
/// key-swap interleave with encrypted traffic on the same channel —
/// inviter can't derive the AES key until the receiver's pub comes back.
enum RadioFrame: Codable {
    case handshake(Data)
    case sealed(Data)
}
