import Foundation

/// One radio chat message. Ephemeral — never written to MessageDB.
/// Survives only as long as the chat surface is open; on session
/// close the array is dropped. Same shape as the regular `Message`
/// but trimmed: text-only payload, optional reply, optional
/// reactions, no media kinds.
struct RadioMessage: Identifiable, Hashable, Codable {
    let id: String                   // UUID — generated by sender
    let senderDisplayName: String    // anonymous label inside the session
    let isFromMe: Bool
    let text: String
    let timestamp: Date
    /// Reply target's id + the snapshot the sender saw at quote
    /// time. Same forward-compat shape as the regular `Message`'s
    /// reply fields — receiver can re-render the bubble even if
    /// the parent has scrolled off.
    let replyToID: String?
    let replyToSender: String?
    let replyToBody: String?
    /// Reactions in the form `[reactor display name: asset name]`.
    /// One per name — toggling sends a fresh wire frame, recipient
    /// merges by name.
    var reactions: [String: String]
}

/// Wire format for messages sent over a `MCSession`. We send JSON
/// blobs (one per logical event) so adding new event types is a
/// dictionary addition, not a binary-format change. Apple's MC
/// already does TLS — this layer is purely the application
/// envelope.
enum RadioPayload: Codable {
    case message(RadioMessage)
    case reaction(messageID: String, reactor: String, asset: String?)
    case challenge(roomID: String, ciphertext: Data)  // password gate
    case challengeAck(roomID: String, ok: Bool)
    case roster(displayName: String)                  // self-introduce on join
    /// Push-to-talk single audio packet. `data` is one AAC-LC frame
    /// (1024 PCM samples @ 16 kHz mono, ~24 kbps) — sealed via the
    /// session AES-GCM key just like every other payload, but sent
    /// `.unreliable` over MC for latency. `speaker` is the local
    /// display name used to key per-sender mixer inputs on receive.
    /// Drop-tolerant by design: a missed packet = a brief gap, not
    /// a stalled stream.
    case voiceFrame(speaker: String, seq: UInt32, data: Data)
    /// Sent reliably right before the first frame goes out. Lets
    /// receivers preallocate the player node and surface the
    /// "X is talking" pill immediately, without waiting on the
    /// first audio packet (which may be unreliable-dropped).
    case voiceTalkStart(speaker: String)
    /// Sent reliably right after the user releases the PTT button.
    /// Tears down the receiver-side player node for this speaker.
    case voiceTalkStop(speaker: String)
}

/// Outer frame wrapper for everything that goes on the wire.
/// Two variants:
///
///   - `.handshake(pub)` — raw Curve25519 public key, plaintext.
///     Used by 1:1 sessions to swap ephemeral keys *after* the
///     MC link is up (Apple's TLS still protects the bytes from
///     anyone outside the session). Both sides send their pub
///     immediately on `.connected`; once the other side's pub
///     arrives, ECDH derives the session key and subsequent
///     traffic switches to `.sealed`.
///
///   - `.sealed(data)` — AES-GCM ciphertext over a JSON-encoded
///     `RadioPayload`. Used for every "real" event (message,
///     reaction, roster).
///
/// Why a separate frame layer: the inviter doesn't have the
/// receiver's pub at invite-time, so they can't derive the AES key
/// either — the receiver has to send theirs back through the
/// established session. A single ciphertext-only protocol would
/// chicken-and-egg this. Tagged frames let us interleave the
/// plaintext key-swap with encrypted application traffic on the
/// same wire.
enum RadioFrame: Codable {
    case handshake(Data)
    case sealed(Data)
}
