import Foundation

/// Per-pack emoticon manifest. Each cosmetic-smileys kind ships a
/// fixed list of (asset, name, primary shortcode) entries. Equipping
/// the pack adds these on top of the default Kolobok palette — no
/// replacement, no exclusivity, per the smiley-pack rule.
///
/// When a new smiley pack is added on the server, register its kind
/// id and the contained gif filenames here so the client can surface
/// them in the chat picker. The asset filenames must match basenames
/// of files bundled into the iOS Resources tree (xcodegen flattens
/// the `Items/cosm1` subfolder to the .app root, so a plain
/// `Bundle.main.url(forResource:withExtension:)` lookup hits them).
enum CosmeticPacks {
    struct Entry: Hashable {
        let asset: String
        let name: String
        let primaryCode: String
    }

    private static let manifest: [String: [Entry]] = [
        "forum_classics": [
            Entry(asset: "banana",   name: "Banana dance", primaryCode: ":banana:"),
            Entry(asset: "coolblue", name: "Cool blue",    primaryCode: ":coolblue:"),
            Entry(asset: "hail",     name: "Hail",         primaryCode: ":hail:"),
            Entry(asset: "hwluxx",   name: "Hwluxx",       primaryCode: ":hwluxx:"),
            Entry(asset: "mad",      name: "Mad",          primaryCode: ":mad:"),
            Entry(asset: "wallbash", name: "Wallbash",     primaryCode: ":wallbash:"),
        ],
        "crayons_pack": [
            Entry(asset: "crayons_001", name: "Crayons #1", primaryCode: ":crayons_001:"),
            Entry(asset: "crayons_002", name: "Crayons #2", primaryCode: ":crayons_002:"),
            Entry(asset: "crayons_003", name: "Crayons #3", primaryCode: ":crayons_003:"),
            Entry(asset: "crayons_004", name: "Crayons #4", primaryCode: ":crayons_004:"),
            Entry(asset: "crayons_005", name: "Crayons #5", primaryCode: ":crayons_005:"),
            Entry(asset: "crayons_006", name: "Crayons #6", primaryCode: ":crayons_006:"),
            Entry(asset: "crayons_007", name: "Crayons #7", primaryCode: ":crayons_007:"),
            Entry(asset: "crayons_008", name: "Crayons #8", primaryCode: ":crayons_008:"),
            Entry(asset: "crayons_009", name: "Crayons #9", primaryCode: ":crayons_009:"),
            Entry(asset: "crayons_010", name: "Crayons #10", primaryCode: ":crayons_010:"),
            Entry(asset: "crayons_011", name: "Crayons #11", primaryCode: ":crayons_011:"),
            Entry(asset: "crayons_012", name: "Crayons #12", primaryCode: ":crayons_012:"),
            Entry(asset: "crayons_013", name: "Crayons #13", primaryCode: ":crayons_013:"),
            Entry(asset: "crayons_014", name: "Crayons #14", primaryCode: ":crayons_014:"),
            Entry(asset: "crayons_015", name: "Crayons #15", primaryCode: ":crayons_015:"),
            Entry(asset: "crayons_016", name: "Crayons #16", primaryCode: ":crayons_016:"),
            Entry(asset: "crayons_017", name: "Crayons #17", primaryCode: ":crayons_017:"),
            Entry(asset: "crayons_018", name: "Crayons #18", primaryCode: ":crayons_018:"),
            Entry(asset: "crayons_019", name: "Crayons #19", primaryCode: ":crayons_019:"),
            Entry(asset: "crayons_020", name: "Crayons #20", primaryCode: ":crayons_020:"),
            Entry(asset: "crayons_021", name: "Crayons #21", primaryCode: ":crayons_021:"),
            Entry(asset: "crayons_022", name: "Crayons #22", primaryCode: ":crayons_022:"),
            Entry(asset: "crayons_023", name: "Crayons #23", primaryCode: ":crayons_023:"),
            Entry(asset: "crayons_024", name: "Crayons #24", primaryCode: ":crayons_024:"),
            Entry(asset: "crayons_025", name: "Crayons #25", primaryCode: ":crayons_025:"),
            Entry(asset: "crayons_026", name: "Crayons #26", primaryCode: ":crayons_026:"),
            Entry(asset: "crayons_027", name: "Crayons #27", primaryCode: ":crayons_027:"),
            Entry(asset: "crayons_028", name: "Crayons #28", primaryCode: ":crayons_028:"),
            Entry(asset: "crayons_029", name: "Crayons #29", primaryCode: ":crayons_029:"),
            Entry(asset: "crayons_030", name: "Crayons #30", primaryCode: ":crayons_030:"),
            Entry(asset: "crayons_031", name: "Crayons #31", primaryCode: ":crayons_031:"),
            Entry(asset: "crayons_032", name: "Crayons #32", primaryCode: ":crayons_032:"),
            Entry(asset: "crayons_033", name: "Crayons #33", primaryCode: ":crayons_033:"),
            Entry(asset: "crayons_034", name: "Crayons #34", primaryCode: ":crayons_034:"),
            Entry(asset: "crayons_035", name: "Crayons #35", primaryCode: ":crayons_035:"),
            Entry(asset: "crayons_036", name: "Crayons #36", primaryCode: ":crayons_036:"),
            Entry(asset: "crayons_037", name: "Crayons #37", primaryCode: ":crayons_037:"),
            Entry(asset: "crayons_038", name: "Crayons #38", primaryCode: ":crayons_038:"),
            Entry(asset: "crayons_039", name: "Crayons #39", primaryCode: ":crayons_039:"),
            Entry(asset: "crayons_040", name: "Crayons #40", primaryCode: ":crayons_040:"),
            Entry(asset: "crayons_041", name: "Crayons #41", primaryCode: ":crayons_041:"),
            Entry(asset: "crayons_042", name: "Crayons #42", primaryCode: ":crayons_042:"),
            Entry(asset: "crayons_043", name: "Crayons #43", primaryCode: ":crayons_043:"),
            Entry(asset: "crayons_044", name: "Crayons #44", primaryCode: ":crayons_044:"),
            Entry(asset: "crayons_045", name: "Crayons #45", primaryCode: ":crayons_045:"),
            Entry(asset: "crayons_046", name: "Crayons #46", primaryCode: ":crayons_046:"),
            Entry(asset: "crayons_047", name: "Crayons #47", primaryCode: ":crayons_047:"),
            Entry(asset: "crayons_048", name: "Crayons #48", primaryCode: ":crayons_048:"),
            Entry(asset: "crayons_049", name: "Crayons #49", primaryCode: ":crayons_049:"),
            Entry(asset: "crayons_050", name: "Crayons #50", primaryCode: ":crayons_050:"),
            Entry(asset: "crayons_051", name: "Crayons #51", primaryCode: ":crayons_051:"),
            Entry(asset: "crayons_052", name: "Crayons #52", primaryCode: ":crayons_052:"),
            Entry(asset: "crayons_053", name: "Crayons #53", primaryCode: ":crayons_053:"),
            Entry(asset: "crayons_054", name: "Crayons #54", primaryCode: ":crayons_054:"),
            Entry(asset: "crayons_055", name: "Crayons #55", primaryCode: ":crayons_055:"),
            Entry(asset: "crayons_056", name: "Crayons #56", primaryCode: ":crayons_056:"),
            Entry(asset: "crayons_057", name: "Crayons #57", primaryCode: ":crayons_057:"),
            Entry(asset: "crayons_058", name: "Crayons #58", primaryCode: ":crayons_058:"),
            Entry(asset: "crayons_059", name: "Crayons #59", primaryCode: ":crayons_059:"),
            Entry(asset: "crayons_060", name: "Crayons #60", primaryCode: ":crayons_060:"),
            Entry(asset: "crayons_061", name: "Crayons #61", primaryCode: ":crayons_061:"),
            Entry(asset: "crayons_062", name: "Crayons #62", primaryCode: ":crayons_062:"),
            Entry(asset: "crayons_063", name: "Crayons #63", primaryCode: ":crayons_063:"),
            Entry(asset: "crayons_064", name: "Crayons #64", primaryCode: ":crayons_064:"),
            Entry(asset: "crayons_065", name: "Crayons #65", primaryCode: ":crayons_065:"),
            Entry(asset: "crayons_066", name: "Crayons #66", primaryCode: ":crayons_066:"),
            Entry(asset: "crayons_067", name: "Crayons #67", primaryCode: ":crayons_067:"),
            Entry(asset: "crayons_068", name: "Crayons #68", primaryCode: ":crayons_068:"),
            Entry(asset: "crayons_069", name: "Crayons #69", primaryCode: ":crayons_069:"),
            Entry(asset: "crayons_070", name: "Crayons #70", primaryCode: ":crayons_070:"),
            Entry(asset: "crayons_071", name: "Crayons #71", primaryCode: ":crayons_071:"),
            Entry(asset: "crayons_072", name: "Crayons #72", primaryCode: ":crayons_072:"),
            Entry(asset: "crayons_073", name: "Crayons #73", primaryCode: ":crayons_073:"),
            Entry(asset: "crayons_074", name: "Crayons #74", primaryCode: ":crayons_074:"),
            Entry(asset: "crayons_075", name: "Crayons #75", primaryCode: ":crayons_075:"),
            Entry(asset: "crayons_076", name: "Crayons #76", primaryCode: ":crayons_076:"),
            Entry(asset: "crayons_077", name: "Crayons #77", primaryCode: ":crayons_077:"),
            Entry(asset: "crayons_078", name: "Crayons #78", primaryCode: ":crayons_078:"),
            Entry(asset: "crayons_079", name: "Crayons #79", primaryCode: ":crayons_079:"),
            Entry(asset: "crayons_080", name: "Crayons #80", primaryCode: ":crayons_080:"),
            Entry(asset: "crayons_081", name: "Crayons #81", primaryCode: ":crayons_081:"),
            Entry(asset: "crayons_082", name: "Crayons #82", primaryCode: ":crayons_082:"),
            Entry(asset: "crayons_083", name: "Crayons #83", primaryCode: ":crayons_083:"),
            Entry(asset: "crayons_084", name: "Crayons #84", primaryCode: ":crayons_084:"),
            Entry(asset: "crayons_085", name: "Crayons #85", primaryCode: ":crayons_085:"),
            Entry(asset: "crayons_086", name: "Crayons #86", primaryCode: ":crayons_086:"),
            Entry(asset: "crayons_087", name: "Crayons #87", primaryCode: ":crayons_087:"),
            Entry(asset: "crayons_088", name: "Crayons #88", primaryCode: ":crayons_088:"),
            Entry(asset: "crayons_089", name: "Crayons #89", primaryCode: ":crayons_089:"),
            Entry(asset: "crayons_090", name: "Crayons #90", primaryCode: ":crayons_090:"),
            Entry(asset: "crayons_091", name: "Crayons #91", primaryCode: ":crayons_091:"),
            Entry(asset: "crayons_092", name: "Crayons #92", primaryCode: ":crayons_092:"),
            Entry(asset: "crayons_093", name: "Crayons #93", primaryCode: ":crayons_093:"),
            Entry(asset: "crayons_094", name: "Crayons #94", primaryCode: ":crayons_094:"),
            Entry(asset: "crayons_095", name: "Crayons #95", primaryCode: ":crayons_095:"),
            Entry(asset: "crayons_096", name: "Crayons #96", primaryCode: ":crayons_096:"),
            Entry(asset: "crayons_097", name: "Crayons #97", primaryCode: ":crayons_097:"),
            Entry(asset: "crayons_098", name: "Crayons #98", primaryCode: ":crayons_098:"),
            Entry(asset: "crayons_099", name: "Crayons #99", primaryCode: ":crayons_099:"),
            Entry(asset: "crayons_100", name: "Crayons #100", primaryCode: ":crayons_100:"),
            Entry(asset: "crayons_101", name: "Crayons #101", primaryCode: ":crayons_101:"),
            Entry(asset: "crayons_102", name: "Crayons #102", primaryCode: ":crayons_102:"),
            Entry(asset: "crayons_103", name: "Crayons #103", primaryCode: ":crayons_103:"),
            Entry(asset: "crayons_104", name: "Crayons #104", primaryCode: ":crayons_104:"),
            Entry(asset: "crayons_105", name: "Crayons #105", primaryCode: ":crayons_105:"),
            Entry(asset: "crayons_106", name: "Crayons #106", primaryCode: ":crayons_106:"),
            Entry(asset: "crayons_107", name: "Crayons #107", primaryCode: ":crayons_107:"),
            Entry(asset: "crayons_108", name: "Crayons #108", primaryCode: ":crayons_108:"),
            Entry(asset: "crayons_109", name: "Crayons #109", primaryCode: ":crayons_109:"),
            Entry(asset: "crayons_110", name: "Crayons #110", primaryCode: ":crayons_110:"),
            Entry(asset: "crayons_111", name: "Crayons #111", primaryCode: ":crayons_111:"),
            Entry(asset: "crayons_112", name: "Crayons #112", primaryCode: ":crayons_112:"),
            Entry(asset: "crayons_113", name: "Crayons #113", primaryCode: ":crayons_113:"),
            Entry(asset: "crayons_114", name: "Crayons #114", primaryCode: ":crayons_114:"),
            Entry(asset: "crayons_115", name: "Crayons #115", primaryCode: ":crayons_115:"),
            Entry(asset: "crayons_116", name: "Crayons #116", primaryCode: ":crayons_116:"),
            Entry(asset: "crayons_117", name: "Crayons #117", primaryCode: ":crayons_117:"),
            Entry(asset: "crayons_118", name: "Crayons #118", primaryCode: ":crayons_118:"),
            Entry(asset: "crayons_119", name: "Crayons #119", primaryCode: ":crayons_119:"),
            Entry(asset: "crayons_120", name: "Crayons #120", primaryCode: ":crayons_120:"),
            Entry(asset: "crayons_121", name: "Crayons #121", primaryCode: ":crayons_121:"),
            Entry(asset: "crayons_122", name: "Crayons #122", primaryCode: ":crayons_122:"),
            Entry(asset: "crayons_123", name: "Crayons #123", primaryCode: ":crayons_123:"),
            Entry(asset: "crayons_124", name: "Crayons #124", primaryCode: ":crayons_124:"),
            Entry(asset: "crayons_125", name: "Crayons #125", primaryCode: ":crayons_125:"),
            Entry(asset: "crayons_126", name: "Crayons #126", primaryCode: ":crayons_126:"),
            Entry(asset: "crayons_127", name: "Crayons #127", primaryCode: ":crayons_127:"),
            Entry(asset: "crayons_128", name: "Crayons #128", primaryCode: ":crayons_128:"),
            Entry(asset: "crayons_129", name: "Crayons #129", primaryCode: ":crayons_129:"),
            Entry(asset: "crayons_130", name: "Crayons #130", primaryCode: ":crayons_130:"),
            Entry(asset: "crayons_131", name: "Crayons #131", primaryCode: ":crayons_131:"),
            Entry(asset: "crayons_132", name: "Crayons #132", primaryCode: ":crayons_132:"),
            Entry(asset: "crayons_133", name: "Crayons #133", primaryCode: ":crayons_133:"),
            Entry(asset: "crayons_134", name: "Crayons #134", primaryCode: ":crayons_134:"),
            Entry(asset: "crayons_135", name: "Crayons #135", primaryCode: ":crayons_135:"),
            Entry(asset: "crayons_136", name: "Crayons #136", primaryCode: ":crayons_136:"),
            Entry(asset: "crayons_137", name: "Crayons #137", primaryCode: ":crayons_137:"),
            Entry(asset: "crayons_138", name: "Crayons #138", primaryCode: ":crayons_138:"),
            Entry(asset: "crayons_139", name: "Crayons #139", primaryCode: ":crayons_139:"),
            Entry(asset: "crayons_140", name: "Crayons #140", primaryCode: ":crayons_140:"),
            Entry(asset: "crayons_141", name: "Crayons #141", primaryCode: ":crayons_141:"),
            Entry(asset: "crayons_142", name: "Crayons #142", primaryCode: ":crayons_142:"),
            Entry(asset: "crayons_143", name: "Crayons #143", primaryCode: ":crayons_143:"),
            Entry(asset: "crayons_144", name: "Crayons #144", primaryCode: ":crayons_144:"),
            Entry(asset: "crayons_145", name: "Crayons #145", primaryCode: ":crayons_145:"),
            Entry(asset: "crayons_146", name: "Crayons #146", primaryCode: ":crayons_146:"),
            Entry(asset: "crayons_147", name: "Crayons #147", primaryCode: ":crayons_147:"),
            Entry(asset: "crayons_148", name: "Crayons #148", primaryCode: ":crayons_148:"),
            Entry(asset: "crayons_149", name: "Crayons #149", primaryCode: ":crayons_149:"),
            Entry(asset: "crayons_150", name: "Crayons #150", primaryCode: ":crayons_150:"),
        ],
        "halloween_pack": [
            Entry(asset: "halloween_001", name: "Halloween #1", primaryCode: ":halloween_001:"),
            Entry(asset: "halloween_002", name: "Halloween #2", primaryCode: ":halloween_002:"),
            Entry(asset: "halloween_003", name: "Halloween #3", primaryCode: ":halloween_003:"),
            Entry(asset: "halloween_004", name: "Halloween #4", primaryCode: ":halloween_004:"),
            Entry(asset: "halloween_005", name: "Halloween #5", primaryCode: ":halloween_005:"),
            Entry(asset: "halloween_006", name: "Halloween #6", primaryCode: ":halloween_006:"),
            Entry(asset: "halloween_007", name: "Halloween #7", primaryCode: ":halloween_007:"),
            Entry(asset: "halloween_008", name: "Halloween #8", primaryCode: ":halloween_008:"),
            Entry(asset: "halloween_009", name: "Halloween #9", primaryCode: ":halloween_009:"),
            Entry(asset: "halloween_010", name: "Halloween #10", primaryCode: ":halloween_010:"),
            Entry(asset: "halloween_011", name: "Halloween #11", primaryCode: ":halloween_011:"),
            Entry(asset: "halloween_012", name: "Halloween #12", primaryCode: ":halloween_012:"),
            Entry(asset: "halloween_013", name: "Halloween #13", primaryCode: ":halloween_013:"),
            Entry(asset: "halloween_014", name: "Halloween #14", primaryCode: ":halloween_014:"),
            Entry(asset: "halloween_015", name: "Halloween #15", primaryCode: ":halloween_015:"),
            Entry(asset: "halloween_016", name: "Halloween #16", primaryCode: ":halloween_016:"),
            Entry(asset: "halloween_017", name: "Halloween #17", primaryCode: ":halloween_017:"),
            Entry(asset: "halloween_018", name: "Halloween #18", primaryCode: ":halloween_018:"),
            Entry(asset: "halloween_019", name: "Halloween #19", primaryCode: ":halloween_019:"),
            Entry(asset: "halloween_020", name: "Halloween #20", primaryCode: ":halloween_020:"),
            Entry(asset: "halloween_021", name: "Halloween #21", primaryCode: ":halloween_021:"),
            Entry(asset: "halloween_022", name: "Halloween #22", primaryCode: ":halloween_022:"),
            Entry(asset: "halloween_023", name: "Halloween #23", primaryCode: ":halloween_023:"),
            Entry(asset: "halloween_024", name: "Halloween #24", primaryCode: ":halloween_024:"),
            Entry(asset: "halloween_025", name: "Halloween #25", primaryCode: ":halloween_025:"),
            Entry(asset: "halloween_026", name: "Halloween #26", primaryCode: ":halloween_026:"),
            Entry(asset: "halloween_027", name: "Halloween #27", primaryCode: ":halloween_027:"),
            Entry(asset: "halloween_028", name: "Halloween #28", primaryCode: ":halloween_028:"),
            Entry(asset: "halloween_029", name: "Halloween #29", primaryCode: ":halloween_029:"),
            Entry(asset: "halloween_030", name: "Halloween #30", primaryCode: ":halloween_030:"),
            Entry(asset: "halloween_031", name: "Halloween #31", primaryCode: ":halloween_031:"),
            Entry(asset: "halloween_032", name: "Halloween #32", primaryCode: ":halloween_032:"),
            Entry(asset: "halloween_033", name: "Halloween #33", primaryCode: ":halloween_033:"),
            Entry(asset: "halloween_034", name: "Halloween #34", primaryCode: ":halloween_034:"),
            Entry(asset: "halloween_035", name: "Halloween #35", primaryCode: ":halloween_035:"),
            Entry(asset: "halloween_036", name: "Halloween #36", primaryCode: ":halloween_036:"),
            Entry(asset: "halloween_037", name: "Halloween #37", primaryCode: ":halloween_037:"),
            Entry(asset: "halloween_038", name: "Halloween #38", primaryCode: ":halloween_038:"),
            Entry(asset: "halloween_039", name: "Halloween #39", primaryCode: ":halloween_039:"),
            Entry(asset: "halloween_040", name: "Halloween #40", primaryCode: ":halloween_040:"),
            Entry(asset: "halloween_041", name: "Halloween #41", primaryCode: ":halloween_041:"),
            Entry(asset: "halloween_042", name: "Halloween #42", primaryCode: ":halloween_042:"),
            Entry(asset: "halloween_043", name: "Halloween #43", primaryCode: ":halloween_043:"),
            Entry(asset: "halloween_044", name: "Halloween #44", primaryCode: ":halloween_044:"),
            Entry(asset: "halloween_045", name: "Halloween #45", primaryCode: ":halloween_045:"),
            Entry(asset: "halloween_046", name: "Halloween #46", primaryCode: ":halloween_046:"),
            Entry(asset: "halloween_047", name: "Halloween #47", primaryCode: ":halloween_047:"),
            Entry(asset: "halloween_048", name: "Halloween #48", primaryCode: ":halloween_048:"),
            Entry(asset: "halloween_049", name: "Halloween #49", primaryCode: ":halloween_049:"),
            Entry(asset: "halloween_050", name: "Halloween #50", primaryCode: ":halloween_050:"),
            Entry(asset: "halloween_051", name: "Halloween #51", primaryCode: ":halloween_051:"),
            Entry(asset: "halloween_052", name: "Halloween #52", primaryCode: ":halloween_052:"),
            Entry(asset: "halloween_053", name: "Halloween #53", primaryCode: ":halloween_053:"),
            Entry(asset: "halloween_054", name: "Halloween #54", primaryCode: ":halloween_054:"),
            Entry(asset: "halloween_055", name: "Halloween #55", primaryCode: ":halloween_055:"),
            Entry(asset: "halloween_056", name: "Halloween #56", primaryCode: ":halloween_056:"),
            Entry(asset: "halloween_057", name: "Halloween #57", primaryCode: ":halloween_057:"),
            Entry(asset: "halloween_058", name: "Halloween #58", primaryCode: ":halloween_058:"),
            Entry(asset: "halloween_059", name: "Halloween #59", primaryCode: ":halloween_059:"),
            Entry(asset: "halloween_060", name: "Halloween #60", primaryCode: ":halloween_060:"),
            Entry(asset: "halloween_061", name: "Halloween #61", primaryCode: ":halloween_061:"),
            Entry(asset: "halloween_062", name: "Halloween #62", primaryCode: ":halloween_062:"),
            Entry(asset: "halloween_063", name: "Halloween #63", primaryCode: ":halloween_063:"),
            Entry(asset: "halloween_064", name: "Halloween #64", primaryCode: ":halloween_064:"),
            Entry(asset: "halloween_065", name: "Halloween #65", primaryCode: ":halloween_065:"),
            Entry(asset: "halloween_066", name: "Halloween #66", primaryCode: ":halloween_066:"),
            Entry(asset: "halloween_067", name: "Halloween #67", primaryCode: ":halloween_067:"),
            Entry(asset: "halloween_068", name: "Halloween #68", primaryCode: ":halloween_068:"),
            Entry(asset: "halloween_069", name: "Halloween #69", primaryCode: ":halloween_069:"),
            Entry(asset: "halloween_070", name: "Halloween #70", primaryCode: ":halloween_070:"),
            Entry(asset: "halloween_071", name: "Halloween #71", primaryCode: ":halloween_071:"),
            Entry(asset: "halloween_072", name: "Halloween #72", primaryCode: ":halloween_072:"),
            Entry(asset: "halloween_073", name: "Halloween #73", primaryCode: ":halloween_073:"),
            Entry(asset: "halloween_074", name: "Halloween #74", primaryCode: ":halloween_074:"),
            Entry(asset: "halloween_075", name: "Halloween #75", primaryCode: ":halloween_075:"),
            Entry(asset: "halloween_076", name: "Halloween #76", primaryCode: ":halloween_076:"),
            Entry(asset: "halloween_077", name: "Halloween #77", primaryCode: ":halloween_077:"),
            Entry(asset: "halloween_078", name: "Halloween #78", primaryCode: ":halloween_078:"),
            Entry(asset: "halloween_079", name: "Halloween #79", primaryCode: ":halloween_079:"),
            Entry(asset: "halloween_080", name: "Halloween #80", primaryCode: ":halloween_080:"),
            Entry(asset: "halloween_081", name: "Halloween #81", primaryCode: ":halloween_081:"),
            Entry(asset: "halloween_082", name: "Halloween #82", primaryCode: ":halloween_082:"),
            Entry(asset: "halloween_083", name: "Halloween #83", primaryCode: ":halloween_083:"),
            Entry(asset: "halloween_084", name: "Halloween #84", primaryCode: ":halloween_084:"),
            Entry(asset: "halloween_085", name: "Halloween #85", primaryCode: ":halloween_085:"),
            Entry(asset: "halloween_086", name: "Halloween #86", primaryCode: ":halloween_086:"),
            Entry(asset: "halloween_087", name: "Halloween #87", primaryCode: ":halloween_087:"),
            Entry(asset: "halloween_088", name: "Halloween #88", primaryCode: ":halloween_088:"),
            Entry(asset: "halloween_089", name: "Halloween #89", primaryCode: ":halloween_089:"),
            Entry(asset: "halloween_090", name: "Halloween #90", primaryCode: ":halloween_090:"),
            Entry(asset: "halloween_091", name: "Halloween #91", primaryCode: ":halloween_091:"),
            Entry(asset: "halloween_092", name: "Halloween #92", primaryCode: ":halloween_092:"),
            Entry(asset: "halloween_093", name: "Halloween #93", primaryCode: ":halloween_093:"),
            Entry(asset: "halloween_094", name: "Halloween #94", primaryCode: ":halloween_094:"),
            Entry(asset: "halloween_095", name: "Halloween #95", primaryCode: ":halloween_095:"),
            Entry(asset: "halloween_096", name: "Halloween #96", primaryCode: ":halloween_096:"),
            Entry(asset: "halloween_097", name: "Halloween #97", primaryCode: ":halloween_097:"),
            Entry(asset: "halloween_098", name: "Halloween #98", primaryCode: ":halloween_098:"),
            Entry(asset: "halloween_099", name: "Halloween #99", primaryCode: ":halloween_099:"),
            Entry(asset: "halloween_100", name: "Halloween #100", primaryCode: ":halloween_100:"),
            Entry(asset: "halloween_101", name: "Halloween #101", primaryCode: ":halloween_101:"),
            Entry(asset: "halloween_102", name: "Halloween #102", primaryCode: ":halloween_102:"),
            Entry(asset: "halloween_103", name: "Halloween #103", primaryCode: ":halloween_103:"),
            Entry(asset: "halloween_104", name: "Halloween #104", primaryCode: ":halloween_104:"),
            Entry(asset: "halloween_105", name: "Halloween #105", primaryCode: ":halloween_105:"),
            Entry(asset: "halloween_106", name: "Halloween #106", primaryCode: ":halloween_106:"),
            Entry(asset: "halloween_107", name: "Halloween #107", primaryCode: ":halloween_107:"),
            Entry(asset: "halloween_108", name: "Halloween #108", primaryCode: ":halloween_108:"),
            Entry(asset: "halloween_109", name: "Halloween #109", primaryCode: ":halloween_109:"),
            Entry(asset: "halloween_110", name: "Halloween #110", primaryCode: ":halloween_110:"),
            Entry(asset: "halloween_111", name: "Halloween #111", primaryCode: ":halloween_111:"),
            Entry(asset: "halloween_112", name: "Halloween #112", primaryCode: ":halloween_112:"),
            Entry(asset: "halloween_113", name: "Halloween #113", primaryCode: ":halloween_113:"),
            Entry(asset: "halloween_114", name: "Halloween #114", primaryCode: ":halloween_114:"),
            Entry(asset: "halloween_115", name: "Halloween #115", primaryCode: ":halloween_115:"),
            Entry(asset: "halloween_116", name: "Halloween #116", primaryCode: ":halloween_116:"),
            Entry(asset: "halloween_117", name: "Halloween #117", primaryCode: ":halloween_117:"),
            Entry(asset: "halloween_118", name: "Halloween #118", primaryCode: ":halloween_118:"),
            Entry(asset: "halloween_119", name: "Halloween #119", primaryCode: ":halloween_119:"),
            Entry(asset: "halloween_120", name: "Halloween #120", primaryCode: ":halloween_120:"),
            Entry(asset: "halloween_121", name: "Halloween #121", primaryCode: ":halloween_121:"),
            Entry(asset: "halloween_122", name: "Halloween #122", primaryCode: ":halloween_122:"),
            Entry(asset: "halloween_123", name: "Halloween #123", primaryCode: ":halloween_123:"),
            Entry(asset: "halloween_124", name: "Halloween #124", primaryCode: ":halloween_124:"),
            Entry(asset: "halloween_125", name: "Halloween #125", primaryCode: ":halloween_125:"),
            Entry(asset: "halloween_126", name: "Halloween #126", primaryCode: ":halloween_126:"),
            Entry(asset: "halloween_127", name: "Halloween #127", primaryCode: ":halloween_127:"),
            Entry(asset: "halloween_128", name: "Halloween #128", primaryCode: ":halloween_128:"),
            Entry(asset: "halloween_129", name: "Halloween #129", primaryCode: ":halloween_129:"),
            Entry(asset: "halloween_130", name: "Halloween #130", primaryCode: ":halloween_130:"),
            Entry(asset: "halloween_131", name: "Halloween #131", primaryCode: ":halloween_131:"),
            Entry(asset: "halloween_132", name: "Halloween #132", primaryCode: ":halloween_132:"),
            Entry(asset: "halloween_133", name: "Halloween #133", primaryCode: ":halloween_133:"),
            Entry(asset: "halloween_134", name: "Halloween #134", primaryCode: ":halloween_134:"),
            Entry(asset: "halloween_135", name: "Halloween #135", primaryCode: ":halloween_135:"),
            Entry(asset: "halloween_136", name: "Halloween #136", primaryCode: ":halloween_136:"),
            Entry(asset: "halloween_137", name: "Halloween #137", primaryCode: ":halloween_137:"),
            Entry(asset: "halloween_138", name: "Halloween #138", primaryCode: ":halloween_138:"),
            Entry(asset: "halloween_139", name: "Halloween #139", primaryCode: ":halloween_139:"),
            Entry(asset: "halloween_140", name: "Halloween #140", primaryCode: ":halloween_140:"),
            Entry(asset: "halloween_141", name: "Halloween #141", primaryCode: ":halloween_141:"),
            Entry(asset: "halloween_142", name: "Halloween #142", primaryCode: ":halloween_142:"),
            Entry(asset: "halloween_143", name: "Halloween #143", primaryCode: ":halloween_143:"),
            Entry(asset: "halloween_144", name: "Halloween #144", primaryCode: ":halloween_144:"),
            Entry(asset: "halloween_145", name: "Halloween #145", primaryCode: ":halloween_145:"),
            Entry(asset: "halloween_146", name: "Halloween #146", primaryCode: ":halloween_146:"),
            Entry(asset: "halloween_147", name: "Halloween #147", primaryCode: ":halloween_147:"),
            Entry(asset: "halloween_148", name: "Halloween #148", primaryCode: ":halloween_148:"),
            Entry(asset: "halloween_149", name: "Halloween #149", primaryCode: ":halloween_149:"),
            Entry(asset: "halloween_150", name: "Halloween #150", primaryCode: ":halloween_150:"),
            Entry(asset: "halloween_151", name: "Halloween #151", primaryCode: ":halloween_151:"),
            Entry(asset: "halloween_152", name: "Halloween #152", primaryCode: ":halloween_152:"),
            Entry(asset: "halloween_153", name: "Halloween #153", primaryCode: ":halloween_153:"),
            Entry(asset: "halloween_154", name: "Halloween #154", primaryCode: ":halloween_154:"),
            Entry(asset: "halloween_155", name: "Halloween #155", primaryCode: ":halloween_155:"),
            Entry(asset: "halloween_156", name: "Halloween #156", primaryCode: ":halloween_156:"),
            Entry(asset: "halloween_157", name: "Halloween #157", primaryCode: ":halloween_157:"),
            Entry(asset: "halloween_158", name: "Halloween #158", primaryCode: ":halloween_158:"),
            Entry(asset: "halloween_159", name: "Halloween #159", primaryCode: ":halloween_159:"),
            Entry(asset: "halloween_160", name: "Halloween #160", primaryCode: ":halloween_160:"),
            Entry(asset: "halloween_161", name: "Halloween #161", primaryCode: ":halloween_161:"),
            Entry(asset: "halloween_162", name: "Halloween #162", primaryCode: ":halloween_162:"),
            Entry(asset: "halloween_163", name: "Halloween #163", primaryCode: ":halloween_163:"),
            Entry(asset: "halloween_164", name: "Halloween #164", primaryCode: ":halloween_164:"),
            Entry(asset: "halloween_165", name: "Halloween #165", primaryCode: ":halloween_165:"),
            Entry(asset: "halloween_166", name: "Halloween #166", primaryCode: ":halloween_166:"),
            Entry(asset: "halloween_167", name: "Halloween #167", primaryCode: ":halloween_167:"),
            Entry(asset: "halloween_168", name: "Halloween #168", primaryCode: ":halloween_168:"),
            Entry(asset: "halloween_169", name: "Halloween #169", primaryCode: ":halloween_169:"),
            Entry(asset: "halloween_170", name: "Halloween #170", primaryCode: ":halloween_170:"),
            Entry(asset: "halloween_171", name: "Halloween #171", primaryCode: ":halloween_171:"),
            Entry(asset: "halloween_172", name: "Halloween #172", primaryCode: ":halloween_172:"),
            Entry(asset: "halloween_173", name: "Halloween #173", primaryCode: ":halloween_173:"),
            Entry(asset: "halloween_174", name: "Halloween #174", primaryCode: ":halloween_174:"),
            Entry(asset: "halloween_175", name: "Halloween #175", primaryCode: ":halloween_175:"),
            Entry(asset: "halloween_176", name: "Halloween #176", primaryCode: ":halloween_176:"),
            Entry(asset: "halloween_177", name: "Halloween #177", primaryCode: ":halloween_177:"),
            Entry(asset: "halloween_178", name: "Halloween #178", primaryCode: ":halloween_178:"),
            Entry(asset: "halloween_179", name: "Halloween #179", primaryCode: ":halloween_179:"),
            Entry(asset: "halloween_180", name: "Halloween #180", primaryCode: ":halloween_180:"),
            Entry(asset: "halloween_181", name: "Halloween #181", primaryCode: ":halloween_181:"),
            Entry(asset: "halloween_182", name: "Halloween #182", primaryCode: ":halloween_182:"),
            Entry(asset: "halloween_183", name: "Halloween #183", primaryCode: ":halloween_183:"),
            Entry(asset: "halloween_184", name: "Halloween #184", primaryCode: ":halloween_184:"),
            Entry(asset: "halloween_185", name: "Halloween #185", primaryCode: ":halloween_185:"),
            Entry(asset: "halloween_186", name: "Halloween #186", primaryCode: ":halloween_186:"),
            Entry(asset: "halloween_187", name: "Halloween #187", primaryCode: ":halloween_187:"),
            Entry(asset: "halloween_188", name: "Halloween #188", primaryCode: ":halloween_188:"),
            Entry(asset: "halloween_189", name: "Halloween #189", primaryCode: ":halloween_189:"),
            Entry(asset: "halloween_190", name: "Halloween #190", primaryCode: ":halloween_190:"),
            Entry(asset: "halloween_191", name: "Halloween #191", primaryCode: ":halloween_191:"),
            Entry(asset: "halloween_192", name: "Halloween #192", primaryCode: ":halloween_192:"),
            Entry(asset: "halloween_193", name: "Halloween #193", primaryCode: ":halloween_193:"),
            Entry(asset: "halloween_194", name: "Halloween #194", primaryCode: ":halloween_194:"),
            Entry(asset: "halloween_195", name: "Halloween #195", primaryCode: ":halloween_195:"),
            Entry(asset: "halloween_196", name: "Halloween #196", primaryCode: ":halloween_196:"),
            Entry(asset: "halloween_197", name: "Halloween #197", primaryCode: ":halloween_197:"),
            Entry(asset: "halloween_198", name: "Halloween #198", primaryCode: ":halloween_198:"),
            Entry(asset: "halloween_199", name: "Halloween #199", primaryCode: ":halloween_199:"),
            Entry(asset: "halloween_200", name: "Halloween #200", primaryCode: ":halloween_200:"),
        ],
        "win95_pack": [
            Entry(asset: "win95_001", name: "Win95 #1", primaryCode: ":win95_001:"),
            Entry(asset: "win95_002", name: "Win95 #2", primaryCode: ":win95_002:"),
            Entry(asset: "win95_003", name: "Win95 #3", primaryCode: ":win95_003:"),
            Entry(asset: "win95_004", name: "Win95 #4", primaryCode: ":win95_004:"),
            Entry(asset: "win95_005", name: "Win95 #5", primaryCode: ":win95_005:"),
            Entry(asset: "win95_006", name: "Win95 #6", primaryCode: ":win95_006:"),
            Entry(asset: "win95_007", name: "Win95 #7", primaryCode: ":win95_007:"),
            Entry(asset: "win95_008", name: "Win95 #8", primaryCode: ":win95_008:"),
            Entry(asset: "win95_009", name: "Win95 #9", primaryCode: ":win95_009:"),
            Entry(asset: "win95_010", name: "Win95 #10", primaryCode: ":win95_010:"),
            Entry(asset: "win95_011", name: "Win95 #11", primaryCode: ":win95_011:"),
            Entry(asset: "win95_012", name: "Win95 #12", primaryCode: ":win95_012:"),
            Entry(asset: "win95_013", name: "Win95 #13", primaryCode: ":win95_013:"),
            Entry(asset: "win95_014", name: "Win95 #14", primaryCode: ":win95_014:"),
            Entry(asset: "win95_015", name: "Win95 #15", primaryCode: ":win95_015:"),
            Entry(asset: "win95_016", name: "Win95 #16", primaryCode: ":win95_016:"),
            Entry(asset: "win95_017", name: "Win95 #17", primaryCode: ":win95_017:"),
            Entry(asset: "win95_018", name: "Win95 #18", primaryCode: ":win95_018:"),
            Entry(asset: "win95_019", name: "Win95 #19", primaryCode: ":win95_019:"),
            Entry(asset: "win95_020", name: "Win95 #20", primaryCode: ":win95_020:"),
            Entry(asset: "win95_021", name: "Win95 #21", primaryCode: ":win95_021:"),
            Entry(asset: "win95_022", name: "Win95 #22", primaryCode: ":win95_022:"),
            Entry(asset: "win95_023", name: "Win95 #23", primaryCode: ":win95_023:"),
            Entry(asset: "win95_024", name: "Win95 #24", primaryCode: ":win95_024:"),
            Entry(asset: "win95_025", name: "Win95 #25", primaryCode: ":win95_025:"),
            Entry(asset: "win95_026", name: "Win95 #26", primaryCode: ":win95_026:"),
            Entry(asset: "win95_027", name: "Win95 #27", primaryCode: ":win95_027:"),
            Entry(asset: "win95_028", name: "Win95 #28", primaryCode: ":win95_028:"),
            Entry(asset: "win95_029", name: "Win95 #29", primaryCode: ":win95_029:"),
            Entry(asset: "win95_030", name: "Win95 #30", primaryCode: ":win95_030:"),
            Entry(asset: "win95_031", name: "Win95 #31", primaryCode: ":win95_031:"),
            Entry(asset: "win95_032", name: "Win95 #32", primaryCode: ":win95_032:"),
            Entry(asset: "win95_033", name: "Win95 #33", primaryCode: ":win95_033:"),
            Entry(asset: "win95_034", name: "Win95 #34", primaryCode: ":win95_034:"),
            Entry(asset: "win95_035", name: "Win95 #35", primaryCode: ":win95_035:"),
            Entry(asset: "win95_036", name: "Win95 #36", primaryCode: ":win95_036:"),
            Entry(asset: "win95_037", name: "Win95 #37", primaryCode: ":win95_037:"),
            Entry(asset: "win95_038", name: "Win95 #38", primaryCode: ":win95_038:"),
            Entry(asset: "win95_039", name: "Win95 #39", primaryCode: ":win95_039:"),
            Entry(asset: "win95_040", name: "Win95 #40", primaryCode: ":win95_040:"),
            Entry(asset: "win95_041", name: "Win95 #41", primaryCode: ":win95_041:"),
            Entry(asset: "win95_042", name: "Win95 #42", primaryCode: ":win95_042:"),
            Entry(asset: "win95_043", name: "Win95 #43", primaryCode: ":win95_043:"),
            Entry(asset: "win95_044", name: "Win95 #44", primaryCode: ":win95_044:"),
            Entry(asset: "win95_045", name: "Win95 #45", primaryCode: ":win95_045:"),
            Entry(asset: "win95_046", name: "Win95 #46", primaryCode: ":win95_046:"),
            Entry(asset: "win95_047", name: "Win95 #47", primaryCode: ":win95_047:"),
            Entry(asset: "win95_048", name: "Win95 #48", primaryCode: ":win95_048:"),
            Entry(asset: "win95_049", name: "Win95 #49", primaryCode: ":win95_049:"),
            Entry(asset: "win95_050", name: "Win95 #50", primaryCode: ":win95_050:"),
            Entry(asset: "win95_051", name: "Win95 #51", primaryCode: ":win95_051:"),
            Entry(asset: "win95_052", name: "Win95 #52", primaryCode: ":win95_052:"),
            Entry(asset: "win95_053", name: "Win95 #53", primaryCode: ":win95_053:"),
            Entry(asset: "win95_054", name: "Win95 #54", primaryCode: ":win95_054:"),
            Entry(asset: "win95_055", name: "Win95 #55", primaryCode: ":win95_055:"),
            Entry(asset: "win95_056", name: "Win95 #56", primaryCode: ":win95_056:"),
            Entry(asset: "win95_057", name: "Win95 #57", primaryCode: ":win95_057:"),
            Entry(asset: "win95_058", name: "Win95 #58", primaryCode: ":win95_058:"),
            Entry(asset: "win95_059", name: "Win95 #59", primaryCode: ":win95_059:"),
            Entry(asset: "win95_060", name: "Win95 #60", primaryCode: ":win95_060:"),
            Entry(asset: "win95_061", name: "Win95 #61", primaryCode: ":win95_061:"),
            Entry(asset: "win95_062", name: "Win95 #62", primaryCode: ":win95_062:"),
            Entry(asset: "win95_063", name: "Win95 #63", primaryCode: ":win95_063:"),
            Entry(asset: "win95_064", name: "Win95 #64", primaryCode: ":win95_064:"),
            Entry(asset: "win95_065", name: "Win95 #65", primaryCode: ":win95_065:"),
            Entry(asset: "win95_066", name: "Win95 #66", primaryCode: ":win95_066:"),
            Entry(asset: "win95_067", name: "Win95 #67", primaryCode: ":win95_067:"),
            Entry(asset: "win95_068", name: "Win95 #68", primaryCode: ":win95_068:"),
            Entry(asset: "win95_069", name: "Win95 #69", primaryCode: ":win95_069:"),
            Entry(asset: "win95_070", name: "Win95 #70", primaryCode: ":win95_070:"),
            Entry(asset: "win95_071", name: "Win95 #71", primaryCode: ":win95_071:"),
            Entry(asset: "win95_072", name: "Win95 #72", primaryCode: ":win95_072:"),
            Entry(asset: "win95_073", name: "Win95 #73", primaryCode: ":win95_073:"),
            Entry(asset: "win95_074", name: "Win95 #74", primaryCode: ":win95_074:"),
            Entry(asset: "win95_075", name: "Win95 #75", primaryCode: ":win95_075:"),
            Entry(asset: "win95_076", name: "Win95 #76", primaryCode: ":win95_076:"),
            Entry(asset: "win95_077", name: "Win95 #77", primaryCode: ":win95_077:"),
            Entry(asset: "win95_078", name: "Win95 #78", primaryCode: ":win95_078:"),
            Entry(asset: "win95_079", name: "Win95 #79", primaryCode: ":win95_079:"),
            Entry(asset: "win95_080", name: "Win95 #80", primaryCode: ":win95_080:"),
            Entry(asset: "win95_081", name: "Win95 #81", primaryCode: ":win95_081:"),
            Entry(asset: "win95_082", name: "Win95 #82", primaryCode: ":win95_082:"),
            Entry(asset: "win95_083", name: "Win95 #83", primaryCode: ":win95_083:"),
            Entry(asset: "win95_084", name: "Win95 #84", primaryCode: ":win95_084:"),
            Entry(asset: "win95_085", name: "Win95 #85", primaryCode: ":win95_085:"),
            Entry(asset: "win95_086", name: "Win95 #86", primaryCode: ":win95_086:"),
            Entry(asset: "win95_087", name: "Win95 #87", primaryCode: ":win95_087:"),
            Entry(asset: "win95_088", name: "Win95 #88", primaryCode: ":win95_088:"),
            Entry(asset: "win95_089", name: "Win95 #89", primaryCode: ":win95_089:"),
            Entry(asset: "win95_090", name: "Win95 #90", primaryCode: ":win95_090:"),
            Entry(asset: "win95_091", name: "Win95 #91", primaryCode: ":win95_091:"),
            Entry(asset: "win95_092", name: "Win95 #92", primaryCode: ":win95_092:"),
            Entry(asset: "win95_093", name: "Win95 #93", primaryCode: ":win95_093:"),
            Entry(asset: "win95_094", name: "Win95 #94", primaryCode: ":win95_094:"),
            Entry(asset: "win95_095", name: "Win95 #95", primaryCode: ":win95_095:"),
            Entry(asset: "win95_096", name: "Win95 #96", primaryCode: ":win95_096:"),
        ],
    ]

    static func entries(for kindID: String) -> [Entry] {
        manifest[kindID] ?? []
    }

    /// Every known cosmetic-pack kind id. Used by the unified
    /// emoticon tokenizer so receivers can render pack-emoji even
    /// without equipping the pack themselves (assets are bundled
    /// into the .app regardless).
    static var allKindIDs: [String] {
        Array(manifest.keys)
    }

    /// Reverse lookup from an emoticon asset name to its pack kind id.
    /// Returns nil for default Kolobok glyphs and unknown assets.
    static func kindID(for asset: String) -> String? {
        if let hit = _assetToKind { return hit[asset] }
        var map: [String: String] = [:]
        for (kindID, entries) in manifest {
            for e in entries { map[e.asset] = kindID }
        }
        _assetToKind = map
        return map[asset]
    }

    private static var _assetToKind: [String: String]? = nil
}
